stages:
  download-mot15:
    cmd: wget "https://motchallenge.net/data/MOT15.zip"
    outs:
      - MOT15.zip
  extract-mot15:
    cmd: unzip MOT15.zip
    deps:
      - MOT15.zip
    outs:
      - MOT15
  parse-mot15:
    cmd: python src/prepare.py MOT15/train data
    deps:
      - MOT15
    params:
      - src/config.py:
          - VAL_SEQUENCES
    outs:
      - data
  tar-mot15:
    cmd: tar -C data -zcvf mot15.tar.gz .
    deps:
      - data
    outs:
      - mot15.tar.gz
